version: '3.7'
services:
    # The Go App
    app:
        build: ./app
        container_name: app
        depends_on:
            - 'mongo'
        environment:
            - PORT=5000
        ports:
            - '5000:5000'
        volumes:
            - './app:/opt/app:cached'
    # MongoDB
    mongo:
        image: 'mongo:4.2.6-bionic'
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./mongodata:/data/db
        restart: always
    # Mongo Express Web-based MongoDB admin interface
    mongo_express:
        image: mongo-express
        container_name: mongo_expressdb
        depends_on:
            - 'mongo'
        ports:
            - '8081:8081'
        restart: always
